[package]
name = "filebrowser-frontend"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { workspace = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true }
wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
gloo-net = { workspace = true }
web-sys = { version = "0.3", features = ["Window", "Location", "WebSocket", "MessageEvent", "BinaryType", "Document", "HtmlDocument"] }
js-sys = { version = "0.3" }
bincode = { workspace = true }
strum = { workspace = true }
filebrowser-types = { workspace = true }

[features]
hydrate = [
    "leptos/hydrate",
]
ssr = [
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
]
