[formatting]
align_entries = false
array_auto_collapse = true
array_auto_expand = true
array_trailing_comma = true
column_width = 100
indent_string = "    "
reorder_arrays = false
reorder_keys = true

[[rule]]
include = ["**/Cargo.toml"]

[rule.formatting]
reorder_keys = true
