[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace]
members = ["app", "backend", "frontend", "types"]
resolver = "3"

[workspace.dependencies]
axum = { version = "0.8", features = ["ws"] }
console_error_panic_hook = { version = "0.1" }
filebrowser-app = { path = "app" }
filebrowser-backend = { path = "backend" }
filebrowser-frontend = { path = "frontend" }
filebrowser-types = { path = "types" }
gloo-net = { version = "0.6", features = ["http", "json"] }
leptos = { version = "0.8" }
leptos_axum = { version = "0.8" }
leptos_meta = { version = "0.8" }
leptos_router = { version = "0.8" }
rand = { version = "0.10" }
reqwest = { version = "0.13", features = ["form", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serenity = { version = "0.12" }
sha2 = { version = "0.11" }
sled = { version = "0.34" }
strum = { version = "0.28", features = ["derive"] }
tokio = { version = "1" }
tower-cookies = { version = "0.11" }
tower-http = { version = "0.6", features = ["trace"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = { version = "2.5", features = ["serde"] }
wasm-bindgen = { version = "0.2" }
wincode = { version = "0.5", features = ["derive"] }

[profile.wasm-release]
codegen-units = 1
inherits = "release"
lto = true
opt-level = 'z'

[[workspace.metadata.leptos]]
bin-default-features = false
bin-features = ["ssr"]
bin-package = "filebrowser-app"
browserquery = "defaults"
lib-default-features = false
lib-features = ["hydrate"]
lib-package = "filebrowser-frontend"
name = "filebrowser"
reload-port = 3001
site-addr = "127.0.0.1:3000"
site-pkg-dir = "pkg"
site-root = "target/site"
style-file = "frontend/output.css"
tailwind-input-file = "frontend/input.css"
