[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = [
  "app",
  "backend",
  "frontend",
  "types",
]

[workspace.dependencies]
leptos = { version = "0.8" }
leptos_meta = { version = "0.8" }
leptos_router = { version = "0.8" }
leptos_axum = { version = "0.8" }
axum = { version = "0.8" }
tokio = { version = "1" }
wasm-bindgen = { version = "0.2" }
console_error_panic_hook = { version = "0.1" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
reqwest = { version = "0.13", features = ["form", "json"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http = { version = "0.6", features = ["trace"] }
tower-cookies = { version = "0.11" }
filebrowser-app = { path = "app" }
filebrowser-backend = { path = "backend" }
filebrowser-frontend = { path = "frontend" }
filebrowser-types = { path = "types" }
rand = { version = "0.10" }
sha2 = { version = "0.11" }
url = { version = "2.5", features = ["serde"] }

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1

[[workspace.metadata.leptos]]
name = "filebrowser"
bin-package = "filebrowser-app"
lib-package = "filebrowser-frontend"
bin-default-features = false
bin-features = ["ssr"]
lib-default-features = false
lib-features = ["hydrate"]
site-root = "target/site"
site-pkg-dir = "pkg"
site-addr = "127.0.0.1:3000"
reload-port = 3001
browserquery = "defaults"
style-file = "frontend/output.css"
tailwind-input-file = "frontend/input.css"
