name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  frontend-build:
    name: frontend build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/frontend-build
      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/

  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  taplo:
    name: TOML format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install taplo
        run: |
          curl -fsSL https://github.com/tamasfe/taplo/releases/latest/download/taplo-linux-x86_64.gz \
            | gzip -d - | install -m 755 /dev/stdin /usr/local/bin/taplo
      - run: taplo fmt --check

  clippy:
    name: clippy
    needs: frontend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: rustup component add clippy
      - run: rustup target add wasm32-unknown-unknown

      - uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - run: cargo clippy --workspace --exclude filebrowser-frontend --all-targets -- -D warnings
      - run: cargo clippy -p filebrowser-frontend --target wasm32-unknown-unknown --all-targets -- -D warnings

  unused-allow:
    name: unused allow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: rustup component add clippy
      - run: cargo install cargo-unused-allow --locked
      - run: cargo-unused-allow --all-targets -- --workspace

  test:
    name: test
    needs: frontend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - run: cargo test --workspace --exclude filebrowser-frontend

  machete:
    name: cargo-machete
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: bnjbvr/cargo-machete@main

  build-binary:
    name: build release binary
    needs: frontend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - run: cargo build --release -p filebrowser-app
